/**
 * Client-facing physics helpers — re-exports shared module.
 * Kept so existing relative imports continue to work.
 */
export {
  generateId,
  randomColor,
  distance,
  getMass,
  getRadius,
  getSpeed,
  getTotalMass,
  getPlayerCenter,
  canEat,
  canEatEjectedMass,
  coversCell,
  lineCircleIntersect,
  getVirusColor,
  distributeVirusPopMass,
  createFood,
  createVirus,
  createBot,
  createBotBehavior,
  splitCell,
  clamp,
  getRandomBotName,
  getMergeTimeMs,
  getFoodRadius,
  WORLD_WIDTH,
  WORLD_HEIGHT,
  INITIAL_RADIUS,
  INITIAL_MASS,
  VIRUS_RADIUS,
  VIRUS_MASS,
  MIN_SPLIT_MASS,
} from '../../shared/physics';

export {
  MAX_CELLS_PER_PLAYER,
  MERGE_BASE_MS as MERGE_TIME,
  FOOD_MASS,
  VIRUS_BONUS_MASS,
  VIRUS_MIN_EAT_MASS,
  VIRUS_MAX_CHARGE,
  SPLIT_BOOST as SPLIT_MAX_SPEED,
  SPLIT_FRICTION as SPLIT_DECELERATION,
  VIRUS_POP_SPEED,
  VIRUS_SPLIT_SPEED,
  EJECT_LOSS as EJECT_MASS_VALUE,
  EJECT_GAIN,
  EJECT_SPEED,
  EJECT_MIN_MASS,
  EJECT_PICKUP_MIN_MASS,
  EJECT_COOLDOWN,
  EJECT_GRACE_PERIOD,
  EJECT_FRICTION,
  EAT_COVERAGE,
  MOVE_LERP,
  VISUAL_GROW_LERP,
  VISUAL_SHRINK_LERP,
  DEFAULT_WS_URL,
  ADMIN_TOKEN,
  ADMIN_NAMES,
  VIRUS_EJECT_COVERAGE,
  CAMERA_ZOOM_REF,
  CAMERA_ZOOM_POWER,
} from '../../shared/constants';

export {
  getSectorAt,
  getSectorLabel,
  getSectorLabelAt,
  getSectorSize,
  getEntityViewRadius,
  isWithinViewRadius,
  isVisibleFromSector,
  SECTOR_COLS,
  SECTOR_ROWS,
  SECTOR_ROW_LABELS,
} from '../../shared/sectors';

